### ISSUE TITLE
API不可用

### ISSUE THREAD

**Issue by Auditor1234** [CRThu/QQMusicDownload#1]
兄弟，api.itooi.cn这个网站已经挂了，有什么办法吗

**Comment by CRThu** [comment]
因为qq音乐限制，本repo接口用的是 [flac.life](https://flac.life) 的网页抓包实现自动化下载链接的，可以直接用网页尝试一下单首歌曲的下载，假如不行可以稍后重新尝试，下载qq音乐需要有会员账号的token调用才能生成vkey，我暂时也没有别的接口用来下载歌曲，可能今天此网站不稳定，十分钟前我尝试了我的脚本可以成功自动下载歌曲。
此网页前端是flac.life, api是https://api.itooi.cn/unlock/{unlockcode}, 假如无法调用和网页前端无法查找就可能是后端挂了或者请求次数过多ip被ban了（后者切换ip能解决）。

**Comment by Auditor1234** [comment]
算了，音乐都下好了
